/* resourcemap.js generated by blorbtool.py */
StaticImageInfo = {
1: {
  "image": 1,
  "url": "Cover.jpg",
  "width": 960,
  "height": 960
}
,
3: {
  "image": 3,
  "url": "Cover.jpg",
  "width": 360,
  "height": 360
}
,
4: {
  "image": 4,
  "url": "interpreter/esploso.jpg",
  "width": 360,
  "height": 360
}
};
